In [27]:
import cv2
import numpy as np

In [50]:
image=cv2.imread("./images/pic4.JPEG")

In [51]:
cv2.imshow("image",image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [52]:
face_cascade=cv2.CascadeClassifier("./haar-algoritm/haarcascade_frontalface_default.xml")

In [53]:
face,number_of_detaection=face_cascade.detectMultiScale2(image,minNeighbors=10)

In [54]:
print(face)

[[103  91  66  66]
 [276  88  65  65]
 [508 126  67  67]
 [385  85  67  67]]


In [55]:
print(number_of_detaection)

[50 47 25 26]


In [48]:
for x,y,h,w in face:
    
    cv2.rectangle(image,(x,y),(x+h,y+w),(80,142,50),2)
    

In [49]:
cv2.imshow("image",image)
cv2.waitKey(0)
cv2.destroyAllWindows()